### ISSUE TITLE
KeyError: 'geoipservice_enabled'

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#27]
I think you forgot to add something to the setup.py file...

----------------------------- BEGIN ERROR ----------------------------------
When attempting to load your configuration file, an error
occurred. This could of happened because of a typo, or an error
in the code. Make sure there aren't any typos in the config file,
and check the traceback below (report it to GitHub for extra internet
points).
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'geoipservice_enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/Python/pyweather/pyweather.py", line 133, in <module>
    geoip_enabled = config.getboolean('UI', 'geoipservice_enabled')
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'geoipservice_enabled' in section: 'UI'
Hey, welcome to PyWeather!
Below, enter a location to check the weather for that location!
Traceback (most recent call last):
  File "/home/benjamin/Python/pyweather/pyweather.py", line 485, in <module>
    if geoip_available is True:
NameError: name 'geoip_available' is not defined
--------------------------- END ERROR ----------------------------

**Comment by o355** [comment]
This is isn't a bug, but moreover a result of development. You'll need to add the option to your config file.
