### ISSUE TITLE
Bug: If a radar image was fetched but returns a 0 byte file, an error occurs.

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#75]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/appJar/appjar.py", line 3494, in <lambda>
    return lambda *args: funcName(param)
  File "pyweather.py", line 4110, in frontend_zoomswitch
    frontend.reloadImage("Viewer", "temp//r10.gif")
  File "/usr/local/lib/python3.5/dist-packages/appJar/appjar.py", line 7042, in reloadImage
    image = self._getImage(imageFile, False)
  File "/usr/local/lib/python3.5/dist-packages/appJar/appjar.py", line 6980, in _getImage
    raise Exception( "Invalid file: " + imagePath + " is not a valid image")
```

Maybe adding an alert would be nice

**Comment by o355** [comment]
Now going to work on this bug.

**Comment by o355** [comment]
Looking at the code, I'm going to add try & except blocks any time an image loads. However, I need to do testing with finding out exactly what error is thrown when trying to load an invalid image.

ETA for a fix is 5/25.

**Comment by o355** [comment]
ETA for a fix is now pushed back to 5/30.

**Comment by o355** [comment]
We have to catch `Exception` in the except block. Work now begins.

**Comment by o355** [comment]
There is now code in PyWeather to catch this exception. And it's everywhere a `frontend.reloadImage` exists.

Issue is fixed.
